### ISSUE TITLE
'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by jacob-baines** [sviehb/jefferson#23]
The following line is not python3 friendly:

https://github.com/sviehb/jefferson/blob/3fafcf2c922aab5d72e2c65e862c6594e41dd700/src/scripts/jefferson#L216

It generates the following error:

```
Traceback (most recent call last):
  File "./jefferson", line 513, in <module>
    main()
  File "./jefferson", line 484, in main
    fs_list = list(scan_fs(content, cstruct.BIG_ENDIAN, verbose=args.verbose))
  File "./jefferson", line 328, in scan_fs
    inode.unpack(content[0 + offset :])
  File "./jefferson", line 216, in unpack
    print(node_data.encode("hex")[:20])
AttributeError: 'bytes' object has no attribute 'encode'
```
This line can be converted to using binascii or just removed altogether since it's a debugging print.

**Comment by sviehb** [comment]
Thank you, it's now merged!
