### ISSUE TITLE
Updated cstruct does not successfully extract the firmware

### ISSUE THREAD

**Issue by dibsy** [sviehb/jefferson#33]
I noticed with the updated cstruct 2.1 ( As on October 2021 ) , jefferson fails to extract the firmware. The workaround I found so far is forcing to use cstruct==1.0

```Fix
Update requirements.txt with the old cstruct version 
cstruct==1.0
```

**Comment by byted** [comment]
thanks! That fixed my issue

**Comment by RICCIARDI-Adrien** [comment]
Same for me, thanks !

**Comment by AndrewFasano** [comment]
I ran into this issue too and #34 fixed it for me.

The full error I got was:
```
Traceback (most recent call last):
  File "/usr/local/bin/jefferson", line 513, in <module>
    main()
  File "/usr/local/bin/jefferson", line 484, in main
    fs_list = list(scan_fs(content, cstruct.BIG_ENDIAN, verbose=args.verbose))
  File "/usr/local/bin/jefferson", line 271, in scan_fs
    set_endianness(endianness)
  File "/usr/local/bin/jefferson", line 262, in set_endianness
    Jffs2_device_node_new.__fmt__ = endianness + Jffs2_device_node_new.__fmt__[1:]
AttributeError: type object 'Jffs2_device_node_new' has no attribute '__fmt__'
```
